spring.application.name=releaseops

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:releaseops}
spring.datasource.username=${POSTGRES_USER:releaseops}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=${SERVER_PORT:8080}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when-authorized
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}